export type ThemeColor = {
    primary: string;
    secondary: string;
    gradient: string;
    glow: string;
    text: string;
    /** Onflix-style: top banner Tailwind class (from-[color]/opacity) */
    banner: string;
};

export const DEFAULT_THEME: ThemeColor = {
    primary: "#8FA7C5",
    secondary: "#1e293b",
    gradient: "from-[#0e1621] via-black to-black",
    glow: "bg-[#0e1621]",
    banner: "from-[#8FA7C5]/18",
    text: "text-white",
};

export const THEME_MAP: Record<string, ThemeColor> = {
    // ── Thể loại ─────────────────────────────────────────
    "hanh-dong": {
        primary: "#ff4d4d",
        secondary: "#3d0d0d",
        gradient: "from-[#3b0d0d] via-black to-black",
        glow: "bg-[#3d0d0d]",
        banner: "from-[#ff4d4d]/20",
        text: "text-white",
    },
    "gay-can": {
        primary: "#e53e3e",
        secondary: "#3d0d0d",
        gradient: "from-[#3b0d0d] via-black to-black",
        glow: "bg-[#3d0d0d]",
        banner: "from-[#e53e3e]/22",
        text: "text-white",
    },
    "tinh-cam": {
        primary: "#ff75a0",
        secondary: "#3d1b3b",
        gradient: "from-[#3d1b3b] via-black to-black",
        glow: "bg-[#3d1b3b]",
        banner: "from-[#ff75a0]/18",
        text: "text-white",
    },
    "co-trang": {
        primary: "#f4c84a",
        secondary: "#3d2e0a",
        gradient: "from-[#3d2e0a] via-black to-black",
        glow: "bg-[#3d2e0a]",
        banner: "from-[#f4c84a]/16",
        text: "text-white",
    },
    "kinh-di": {
        primary: "#a855f7",
        secondary: "#1a1a1a",
        gradient: "from-[#1a1a1a] via-black to-black",
        glow: "bg-[#1a1a1a]",
        banner: "from-[#a855f7]/18",
        text: "text-white",
    },
    "hoat-hinh": {
        primary: "#00d2ff",
        secondary: "#0d2a4a",
        gradient: "from-[#0d2a4a] via-black to-black",
        glow: "bg-[#0d2a4a]",
        banner: "from-[#00d2ff]/18",
        text: "text-white",
    },
    "phim-hoat-hinh": {
        primary: "#00d2ff",
        secondary: "#0d2a4a",
        gradient: "from-[#0d2a4a] via-black to-black",
        glow: "bg-[#0d2a4a]",
        banner: "from-[#00d2ff]/18",
        text: "text-white",
    },
    "vien-tuong": {
        primary: "#3b82f6",
        secondary: "#0d1a3b",
        gradient: "from-[#0d1a3b] via-black to-black",
        glow: "bg-[#0d1a3b]",
        banner: "from-[#3b82f6]/20",
        text: "text-white",
    },
    "bi-an": {
        primary: "#8b5cf6",
        secondary: "#1a0d3b",
        gradient: "from-[#1a0d3b] via-black to-black",
        glow: "bg-[#1a0d3b]",
        banner: "from-[#8b5cf6]/22",
        text: "text-white",
    },
    "tam-ly": {
        primary: "#6366f1",
        secondary: "#130d3b",
        gradient: "from-[#130d3b] via-black to-black",
        glow: "bg-[#130d3b]",
        banner: "from-[#6366f1]/20",
        text: "text-white",
    },
    "hinh-su": {
        primary: "#f59e0b",
        secondary: "#2b1a00",
        gradient: "from-[#2b1a00] via-black to-black",
        glow: "bg-[#2b1a00]",
        banner: "from-[#f59e0b]/16",
        text: "text-white",
    },
    "chien-tranh": {
        primary: "#84cc16",
        secondary: "#1a2b0a",
        gradient: "from-[#1a2b0a] via-black to-black",
        glow: "bg-[#1a2b0a]",
        banner: "from-[#84cc16]/16",
        text: "text-white",
    },
    "tai-lieu": {
        primary: "#f97316",
        secondary: "#2b1200",
        gradient: "from-[#2b1200] via-black to-black",
        glow: "bg-[#2b1200]",
        banner: "from-[#f97316]/18",
        text: "text-white",
    },
    "hoc-duong": {
        primary: "#34d399",
        secondary: "#0a2b1a",
        gradient: "from-[#0a2b1a] via-black to-black",
        glow: "bg-[#0a2b1a]",
        banner: "from-[#34d399]/18",
        text: "text-white",
    },
    "hai-huoc": {
        primary: "#fbbf24",
        secondary: "#2b2000",
        gradient: "from-[#2b2000] via-black to-black",
        glow: "bg-[#2b2000]",
        banner: "from-[#fbbf24]/16",
        text: "text-white",
    },
    "vo-thuat": {
        primary: "#ef4444",
        secondary: "#2b0a0a",
        gradient: "from-[#2b0a0a] via-black to-black",
        glow: "bg-[#2b0a0a]",
        banner: "from-[#ef4444]/20",
        text: "text-white",
    },
    "gia-dinh": {
        primary: "#f472b6",
        secondary: "#2b0a1a",
        gradient: "from-[#2b0a1a] via-black to-black",
        glow: "bg-[#2b0a1a]",
        banner: "from-[#f472b6]/18",
        text: "text-white",
    },
    "than-thoai": {
        primary: "#c084fc",
        secondary: "#1e0d3b",
        gradient: "from-[#1e0d3b] via-black to-black",
        glow: "bg-[#1e0d3b]",
        banner: "from-[#c084fc]/20",
        text: "text-white",
    },
    "phim-18": {
        primary: "#f43f5e",
        secondary: "#2b0a10",
        gradient: "from-[#2b0a10] via-black to-black",
        glow: "bg-[#2b0a10]",
        banner: "from-[#f43f5e]/22",
        text: "text-white",
    },

    // ── Quốc gia ─────────────────────────────────────────
    "trung-quoc": {
        primary: "#f4c84a",
        secondary: "#3d2e0a",
        gradient: "from-[#3d2e0a] via-black to-black",
        glow: "bg-[#3d2e0a]",
        banner: "from-[#f4c84a]/16",
        text: "text-white",
    },
    "han-quoc": {
        primary: "#8FA7C5",
        secondary: "#0d1a3b",
        gradient: "from-[#0d1a3b] via-black to-black",
        glow: "bg-[#0d1a3b]",
        banner: "from-[#8FA7C5]/20",
        text: "text-white",
    },
    "au-my": {
        primary: "#ff4d4d",
        secondary: "#3b0d0d",
        gradient: "from-[#3b0d0d] via-black to-black",
        glow: "bg-[#3b0d0d]",
        banner: "from-[#ff4d4d]/20",
        text: "text-white",
    },
    "nhat-ban": {
        primary: "#00d2ff",
        secondary: "#0d2a4a",
        gradient: "from-[#0d2a4a] via-black to-black",
        glow: "bg-[#0d2a4a]",
        banner: "from-[#00d2ff]/18",
        text: "text-white",
    },
    "thai-lan": {
        primary: "#f59e0b",
        secondary: "#2b1a00",
        gradient: "from-[#2b1a00] via-black to-black",
        glow: "bg-[#2b1a00]",
        banner: "from-[#f59e0b]/17",
        text: "text-white",
    },
    "an-do": {
        primary: "#f97316",
        secondary: "#2b1200",
        gradient: "from-[#2b1200] via-black to-black",
        glow: "bg-[#2b1200]",
        banner: "from-[#f97316]/18",
        text: "text-white",
    },
    "viet-nam": {
        primary: "#ef4444",
        secondary: "#2b0a0a",
        gradient: "from-[#2b0a0a] via-black to-black",
        glow: "bg-[#2b0a0a]",
        banner: "from-[#ef4444]/20",
        text: "text-white",
    },
    "phim-han": {
        primary: "#8FA7C5",
        secondary: "#0d1a3b",
        gradient: "from-[#0d1a3b] via-black to-black",
        glow: "bg-[#0d1a3b]",
        banner: "from-[#8FA7C5]/20",
        text: "text-white",
    },
    "phim-trung": {
        primary: "#f4c84a",
        secondary: "#3d2e0a",
        gradient: "from-[#3d2e0a] via-black to-black",
        glow: "bg-[#3d2e0a]",
        banner: "from-[#f4c84a]/16",
        text: "text-white",
    },

    // ── Danh sách ─────────────────────────────────────────
    "phim-le": {
        primary: "#ff4747",
        secondary: "#2b0a0a",
        gradient: "from-[#2b0a0a] via-black to-black",
        glow: "bg-[#2b0a0a]",
        banner: "from-[#ff4747]/20",
        text: "text-white",
    },
    "phim-bo": {
        primary: "#478cff",
        secondary: "#0a1a2b",
        gradient: "from-[#0a1a2b] via-black to-black",
        glow: "bg-[#0a1a2b]",
        banner: "from-[#478cff]/20",
        text: "text-white",
    },
    "phim-moi": {
        primary: "#ffc107",
        secondary: "#2b210a",
        gradient: "from-[#2b210a] via-black to-black",
        glow: "bg-[#2b210a]",
        banner: "from-[#ffc107]/16",
        text: "text-white",
    },
    "phim-moi-cap-nhat": {
        primary: "#00feba",
        secondary: "#0a2b21",
        gradient: "from-[#0a2b21] via-black to-black",
        glow: "bg-[#0a2b21]",
        banner: "from-[#00feba]/16",
        text: "text-white",
    },
    "tv-shows": {
        primary: "#a78bfa",
        secondary: "#1a0d3b",
        gradient: "from-[#1a0d3b] via-black to-black",
        glow: "bg-[#1a0d3b]",
        banner: "from-[#a78bfa]/20",
        text: "text-white",
    },
    "hoat-hinh-list": {
        primary: "#00d2ff",
        secondary: "#0d2a4a",
        gradient: "from-[#0d2a4a] via-black to-black",
        glow: "bg-[#0d2a4a]",
        banner: "from-[#00d2ff]/18",
        text: "text-white",
    },
    "phim-chieu-rap": {
        primary: "#f59e0b",
        secondary: "#2b1a00",
        gradient: "from-[#2b1a00] via-black to-black",
        glow: "bg-[#2b1a00]",
        banner: "from-[#f59e0b]/17",
        text: "text-white",
    },
    "vietsub": {
        primary: "#34d399",
        secondary: "#0a2b1a",
        gradient: "from-[#0a2b1a] via-black to-black",
        glow: "bg-[#0a2b1a]",
        banner: "from-[#34d399]/17",
        text: "text-white",
    },
    "thuyet-minh": {
        primary: "#60a5fa",
        secondary: "#0a1a2b",
        gradient: "from-[#0a1a2b] via-black to-black",
        glow: "bg-[#0a1a2b]",
        banner: "from-[#60a5fa]/18",
        text: "text-white",
    },

    // ── Chức năng ─────────────────────────────────────────
    "tim-kiem": {
        primary: "#00d2ff",
        secondary: "#051a2e",
        gradient: "from-[#051a2e] via-black to-black",
        glow: "bg-[#051a2e]",
        banner: "from-[#00d2ff]/16",
        text: "text-white",
    },
    "loc-phim": {
        primary: "#b100ff",
        secondary: "#1a0d4a",
        gradient: "from-[#1a0d4a] via-black to-black",
        glow: "bg-[#1a0d4a]",
        banner: "from-[#b100ff]/18",
        text: "text-white",
    },
};

export function getThemeBySlug(slug: string): ThemeColor {
    return THEME_MAP[slug] || DEFAULT_THEME;
}
